# This is the yml file that defines the API endpoints
#
# To add a new endpoint, add a new path under paths
# To add a new response object, add a new object under components/schemas
# To add a new tag, add a new tag under tags
#
# For more information about the OpenAPI Specification, see https://swagger.io/specification/
# To debug your yml code, you can use https://editor.swagger.io/

openapi: 3.0.3
info:
  title: compliance-queries-api
  version: "1.0"
  description: The ward's compliance queires endpoints
paths:
  /addresses/{address}:
    get:
      operationId: analysis-address-data
      description: Analyze address
      tags:
        - compliance
      parameters:
        - name: address
          in: path
          description: The address to get
          required: true
          schema:
            type: string
        - name: api
          in: header
          description: The api key
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/AddressAnalysis"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "429":
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /addresses/{address}/transactions:
    get:
      operationId: get-transactions
      description: Get transactions for an address
      tags:
        - transactions
      parameters:
        - name: address
          in: path
          description: The address to get transactions for
          required: true
          schema:
            type: string
        - name: page_size
          in: query
          description: The number of transactions to return
          required: false
          schema:
            type: integer
        - name: page
          in: query
          description: The page of transactions to return
          required: false
          schema:
            type: integer
        - name: transaction_type
          in: query
          description: The type of transactions to return. Default is "combined"
          required: false
          schema:
            type: string
            enum:
              - incoming
              - outgoing
              - combined
              - between
        - name: destination_address
          in: query
          description: The destination address to get transactions for. Only used when transaction_type is "between"
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      transactions:
                        type: array
                        items:
                          $ref: "#/components/schemas/Transaction"
                      total:
                        type: integer
                      page:
                        type: integer
                      page_size:
                        type: integer
  /addresses/{address}/labels:
    get:
      operationId: get-labels
      description: Get labels for an address
      tags:
        - labels
      parameters:
        - name: address
          in: path
          description: The address to get labels for
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      labels:
                        type: array
                        items:
                          $ref: "#/components/schemas/Label"
  /labels/search-labels:
    post:
      operationId: search-labels
      description: Search labels and returns the labels that match the query limited by the set limit
      tags:
        - labels
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                limit:
                  type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  labels:
                    type: array
                    items:
                      $ref: "#/components/schemas/Label"
                    required:
                      - labels

  # Accepts a list of labels and returns a list of categories in {"categories": []} format
  /labels/get-category:
    post:
      operationId: get-category
      description: Get category for a list of labels
      tags:
        - labels
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                labels:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: string
                    required:
                      - categories

components:
  schemas:
    # Address Analysis
    AddressAnalysis:
      type: object
      properties:
        address:
          type: string
        blockchain:
          type: string
        risk:
          type: number
        labels:
          type: array
          items:
            type: string
        timestampScanned:
          type: string
          format: number
        incomingDirectExposure:
          $ref: "#/components/schemas/Exposure"
        incomingIndirectExposure:
          $ref: "#/components/schemas/Exposure"
        outgoingDirectExposure:
          $ref: "#/components/schemas/Exposure"
        outgoingIndirectExposure:
          $ref: "#/components/schemas/Exposure"
      required:
        - address
        - blockchain
        - risk
        - labels
        - timestampScanned
        - incomingDirectExposure
        - incomingIndirectExposure
        - outgoingDirectExposure
        - outgoingIndirectExposure
    Exposure:
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: "#/components/schemas/Category"
        total:
          type: number
      required:
        - categories
        - total
    Category:
      type: object
      properties:
        entities:
          type: array
          items:
            $ref: "#/components/schemas/Entity"
        name:
          type: string
        total:
          type: number
      required:
        - entities
        - name
        - total
    Entity:
      type: object
      properties:
        addresses:
          type: array
          items:
            $ref: "#/components/schemas/Address"
        name:
          type: string
        quantity:
          type: number
      required:
        - addresses
        - name
        - quantity
    Address:
      type: object
      properties:
        hash:
          type: string
        quantity:
          type: number
        paths:
          type: array
          items:
            type: array
            items:
              type: string
      required:
        - hash
        - quantity

    # Transaction
    Output:
      type: object
      properties:
        address:
          type: string
        value:
          type: number
        usdValue:
          type: number
      required:
        - address
        - value
        - usdValue
    Transaction:
      type: object
      properties:
        hash:
          type: string
        value:
          type: number
        currency:
          type: string
        blockNumber:
          type: number
        timestamp:
          type: number
        inputs:
          type: array
          items:
            $ref: "#/components/schemas/Output"
        outputs:
          type: array
          items:
            $ref: "#/components/schemas/Output"
        usdValue:
          type: number
        tokenSymbol:
          type: string
        tokenName:
          type: string
      required:
        - hash
        - value
        - currency
        - blockNumber
        - timestamp
        - inputs
        - outputs
        - usdValue
        - tokenSymbol
        - tokenName

    # Labels
    Label:
      type: object
      properties:
        label:
          type: string
        description:
          type: string
        address:
          type: string
      required:
        - name
        - description
        - address

    # Error
    ErrorResponse:
      type: object
      properties:
        msg:
          type: string

tags:
  - name: compliance
    description: The compliance queires endpoints
  - name: errors
    description: The error responses
  - name: transactions
    description: The transaction endpoints
  - name: labels
    description: The labels endpoints
