/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */
import {
  useMutation
} from 'react-query'
import type {
  MutationFunction,
  UseMutationOptions
} from 'react-query'
import type {
  SearchLabels200
} from '../model/searchLabels200'
import type {
  SearchLabelsBody
} from '../model/searchLabelsBody'
import { instance } from '.././instance';



/**
 * Search labels and returns the labels that match the query limited by the set limit
 */
export const searchLabels = (
    searchLabelsBody: SearchLabelsBody,
 ) => {
      
      
      return instance<SearchLabels200>(
      {url: `/labels/search-labels`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: searchLabelsBody
    },
      );
    }
  


export const getSearchLabelsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchLabels>>, TError,{data: SearchLabelsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof searchLabels>>, TError,{data: SearchLabelsBody}, TContext> => {
 const {mutation: mutationOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof searchLabels>>, {data: SearchLabelsBody}> = (props) => {
          const {data} = props ?? {};

          return  searchLabels(data,)
        }

        


   return  { mutationFn, ...mutationOptions }}

    export type SearchLabelsMutationResult = NonNullable<Awaited<ReturnType<typeof searchLabels>>>
    export type SearchLabelsMutationBody = SearchLabelsBody
    export type SearchLabelsMutationError = unknown

    export const useSearchLabels = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof searchLabels>>, TError,{data: SearchLabelsBody}, TContext>, }
) => {

      const mutationOptions = getSearchLabelsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    