/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */
import type { Address } from './address';

export interface Entity {
  addresses: Address[];
  name: string;
  quantity: number;
}
