/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */

export type GetCategoryParams = {
/**
 * The labels to get categories for
 */
labels: string[];
};
