/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */
import type { GetLabels200Data } from './getLabels200Data';

export type GetLabels200 = {
  data?: GetLabels200Data;
};
