/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */
import type { GetTransactionsTransactionType } from './getTransactionsTransactionType';

export type GetTransactionsParams = {
/**
 * The number of transactions to return
 */
page_size?: number;
/**
 * The page of transactions to return
 */
page?: number;
/**
 * The type of transactions to return. Default is "combined"
 */
transaction_type?: GetTransactionsTransactionType;
/**
 * The destination address to get transactions for. Only used when transaction_type is "between"
 */
destination_address?: string;
};
