/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */

export type GetTransactionsTransactionType = typeof GetTransactionsTransactionType[keyof typeof GetTransactionsTransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetTransactionsTransactionType = {
  incoming: 'incoming',
  outgoing: 'outgoing',
  combined: 'combined',
  between: 'between',
} as const;
