/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */

export type GetTransactionsBetweenAddressesParams = {
/**
 * The source address
 */
src: string;
/**
 * The destination address
 */
dst: string;
/**
 * The page of transactions to return
 */
page?: number;
/**
 * The number of transactions to return
 */
page_size?: number;
};
