/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */

export type TagIndividualAddressParams = {
/**
 * The address to tag
 */
address: string;
/**
 * The tag to add
 */
tag: string;
};
