/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * compliance-queries-api
 * The ward's compliance queires endpoints
 * OpenAPI spec version: 1.0
 */
import type { Output } from './output';

export interface Transaction {
  blockNumber: number;
  currency: string;
  hash: string;
  inputs: Output[];
  outputs: Output[];
  timestamp: number;
  usdValue: number;
  value: number;
}
