# Configuration for deploying to production on merge to development
# For more information, see https://github.com/marketplace/actions/deploy-to-firebase-hosting#options

name: Deploy to Firebase Dev Hosting on merge
"on":
  push:
    branches:
      - development
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GRAPHAPP_DEV }}"
          channelId: live
          projectId: graphapp-dev
