# Configuration for deploy a preview of the PR to a temporary url
# The goal is to be able to test the PR before merging it
# This action is triggered on every PR, regardless of the branch
# The preview url has a lifetime of 7 days
# For more information, see https://github.com/marketplace/actions/deploy-to-firebase-hosting#options

name: Deploy to Firebase Hosting on PR
"on": pull_request

env:
  VITE_WARD_API_BASE_URL: https://wardanalyticsapi.com
  VITE_WARD_API_KEY: ${{ secrets.WARD_API_KEY }}
  VITE_FIREBASE_API_KEY: AIzaSyD1LUGU2RM-bhxKgeYdnzItbwBC0VSTOV0
  VITE_FIREBASE_AUTH_DOMAIN: graphapp-bca04.firebaseapp.com
  VITE_FIREBASE_PROJECT_ID: graphapp-bca04
  VITE_FIREBASE_STORAGE_BUCKET: graphapp-bca04.appspot.com
  VITE_FIREBASE_MESSAGING_SENDER_ID: "1030502540585"
  VITE_FIREBASE_APP_ID: "1:1030502540585:web:cfe727695aad44d0494338"
  # For Google Analytics
  VITE_FIREBASE_MEASUREMENT_ID: G-RYB03B2Q13

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn install && yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GRAPHAPP_BCA04 }}"
          expires: 7d
          projectId: graphapp-bca04
